[package]
name = "hypernova_core"
version = "1.0.0"
authors = []

[addresses]
hypernova_core = "_"

[dev-addresses]
hypernova_core = "0xdead"

[dependencies.SupraFramework]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/supra-framework"

