[package]
name = "access_control"
version = "1.0.0"
authors = []

[addresses]
access_control = "_"

[dev-addresses]
access_control = "0xdead"

[dependencies.SupraFramework]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/supra-framework"
